/**
 * Clave de categoría. Es un `string` para permitir categorías DINÁMICAS creadas
 * desde el panel admin (tabla Supabase `categories`). Las 9 base están abajo en
 * `categories` / `categoryLabels` / `categoryEmoji` y sirven de fallback.
 */
export type ProductCategory = string;

export type ProductType = 'detal' | 'mayorista' | 'ambos';

export interface Product {
  id: string;
  name: string;
  /** Presentación / empaque, separado del nombre. Ej. "10 Unidades", "1 KG". */
  units?: string | null;
  description: string;
  category: ProductCategory;
  type: ProductType;
  /** precio_usd_detal — base USD al detal. */
  price_usd: number;
  /** precio_usd_mayor — USD al mayor (= detal si no hay descuento al mayor). */
  wholesale_price_usd: number;
  /** precio_cop_detal — COP al detal fijado por el cliente. */
  price_cop?: number | null;
  /** precio_cop_mayor — COP al mayor (= detal si no hay descuento al mayor). */
  wholesale_price_cop?: number | null;
  available: boolean;
  image_url: string | null;
  is_best_seller: boolean;
  /**
   * Cantidad mínima del mismo producto que activa la tarifa al mayor.
   * La columna en Supabase es NOT NULL (default 10); si se omite aquí, la lógica
   * de precios cae al default global `WHOLESALE_MIN_QTY` (10).
   */
  limite_unidades_mayor?: number;
  /**
   * Si true, el producto admite servicio de fritos (recargo por bandeja) en
   * venta individual. Por defecto Tequeños y Pasapalos. Combos exentos.
   * La columna en Supabase es NOT NULL (default false), por eso no admite null.
   */
  cobra_frito?: boolean;
}

/*
 * Estructura espejo de precios (economía de frontera CO-VE):
 *   - COP y USD se guardan independientes para evitar pérdidas cambiarias.
 *   - Bs NUNCA se guarda: se calcula en el cliente = precio_usd × tasa_bcv_del_dia.
 *   - El gatillo al mayor se aplica en el carrito: cantidad >= 10 del mismo
 *     producto conmuta a los campos `wholesale_*`. Si mayor == detal, no cambia.
 *
 * Catálogo auditado con el cliente (Jun 2026). Donde el cliente no definió un
 * precio al mayor real, mayor = detal (regla confirmada).
 */
export const products: Product[] = [

  // ─── TEQUEÑOS ─────────────────────────────────────────────
  {
    id: 'tequeno-super-queso',
    name: 'Tequeño Super Queso',
    units: '10 Unidades',
    description: 'Tequeño súper relleno de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 9.00,
    wholesale_price_usd: 9.00,
    price_cop: 25000,
    wholesale_price_cop: 25000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'tequeno-super-byq',
    name: 'Tequeño Super B y Q',
    units: '10 Unidades',
    description: 'Tequeño súper de bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 9.90,
    price_cop: 27000,
    wholesale_price_cop: 27000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-tyq',
    name: 'Tequeño T y Q',
    units: '10 Unidades',
    description: 'Tequeño de tocineta y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 10.00,
    wholesale_price_usd: 10.00,
    price_cop: 28000,
    wholesale_price_cop: 28000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-tradicional-queso-25',
    name: 'Tequeño Tradicional Queso',
    units: '25 Unidades',
    description: 'Tequeño tradicional de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    price_cop: 15000,
    wholesale_price_cop: 15000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'tequeno-tradicional-byq',
    name: 'Tequeño Tradicional B y Q',
    units: '25 Unidades',
    description: 'Tequeño tradicional de bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.32,
    wholesale_price_usd: 7.32,
    price_cop: 17000,
    wholesale_price_cop: 17000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-escolar-queso',
    name: 'Tequeño Escolar Queso',
    units: '10 Unidades',
    description: 'Tequeño tamaño escolar de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.12,
    wholesale_price_usd: 6.12,
    price_cop: 14000,
    wholesale_price_cop: 14000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-escolar-byq',
    name: 'Tequeño Escolar B y Q',
    units: '10 Unidades',
    description: 'Tequeño escolar de bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    price_cop: 15000,
    wholesale_price_cop: 15000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-doble-queso',
    name: 'Tequeño Doble Queso',
    units: '10 Unidades',
    description: 'Tequeño con doble relleno de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.74,
    wholesale_price_usd: 7.74,
    price_cop: 18000,
    wholesale_price_cop: 16000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-doble-surtido',
    name: 'Tequeño Doble Surtido',
    units: '10 Unidades',
    description: 'Tequeño doble con rellenos variados',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 8.61,
    wholesale_price_usd: 8.61,
    price_cop: 20000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-mini-combo',
    name: 'Tequeño Mini Combo',
    units: '25 Unidades',
    description: 'Combo de tequeños mini',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 8000,
    wholesale_price_cop: 7500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-queso',
    name: 'Tequeño Normal de Queso',
    units: '10 Unidades',
    description: 'Tequeño tamaño normal de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.43,
    wholesale_price_usd: 6.43,
    price_cop: 16000,
    wholesale_price_cop: 16000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-byq',
    name: 'Tequeño Normal B y Q',
    units: '10 Unidades',
    description: 'Tequeño normal de bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.11,
    wholesale_price_usd: 7.11,
    price_cop: 18000,
    wholesale_price_cop: 18000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-tyq',
    name: 'Tequeño Normal T y Q',
    units: '10 Unidades',
    description: 'Tequeño normal de tocineta y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.13,
    wholesale_price_usd: 7.13,
    price_cop: 19000,
    wholesale_price_cop: 19000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-jyq',
    name: 'Tequeño Normal J y Q',
    units: '10 Unidades',
    description: 'Tequeño normal de jamón y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.11,
    wholesale_price_usd: 7.11,
    price_cop: 18000,
    wholesale_price_cop: 18000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── PASAPALOS ────────────────────────────────────────────
  {
    id: 'pasapalos-combo',
    name: 'Pasapalos Combo',
    units: '15 Unidades',
    description: 'Combo de pasapalos surtidos',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 8000,
    wholesale_price_cop: 7500,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'pasapalos-pollo-carne',
    name: 'Pasapalos Pollo/Carne',
    units: '15 Unidades',
    description: 'Pasapalos de pollo o de carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.16,
    wholesale_price_usd: 5.16,
    price_cop: 13000,
    wholesale_price_cop: 13000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'bolitas-carne',
    name: 'Bolitas de Carne',
    units: '15 Unidades',
    description: 'Bolitas de carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.16,
    wholesale_price_usd: 5.16,
    price_cop: 15000,
    wholesale_price_cop: 15000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'morcillitas',
    name: 'Morcillitas',
    units: '25 Unidades',
    description: 'Morcillitas',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    price_cop: 17000,
    wholesale_price_cop: 17000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pastelon-pizza',
    name: 'Pastelón Pizza',
    units: '10 Unidades',
    description: 'Pastelón sabor pizza',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.16,
    wholesale_price_usd: 5.16,
    price_cop: 13000,
    wholesale_price_cop: 13000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pastelon-ac',
    name: 'Pastelón Arroz con Carne',
    units: '10 Unidades',
    description: 'Pastel de arroz con carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.58,
    wholesale_price_usd: 5.58,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pastelon-pc',
    name: 'Pastelón Arroz con Pollo',
    units: '10 Unidades',
    description: 'Pastel de arroz con pollo',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.58,
    wholesale_price_usd: 5.58,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── MASAS Y BASES PARA PIZZA ─────────────────────────────
  {
    id: 'masa-1kg',
    name: 'Masa 1 Kg',
    units: '1 KG',
    description: 'Masa fácil artesanal de 1 kilogramo',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.18,
    wholesale_price_usd: 2.95,
    price_cop: 7500,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'masa-750',
    name: 'Masa 750',
    units: '750 g',
    description: 'Masa fácil artesanal de 750 gramos',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 2.37,
    wholesale_price_usd: 2.10,
    price_cop: 5500,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-500',
    name: 'Masa 500',
    units: '500 g',
    description: 'Masa fácil artesanal de 500 gramos',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.50,
    wholesale_price_usd: 1.25,
    price_cop: 3500,
    wholesale_price_cop: 3000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n4',
    name: 'Masa N.4',
    units: '1 Unidad',
    description: 'Masa número 4',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.18,
    wholesale_price_usd: 2.95,
    price_cop: 7500,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n4-h',
    name: 'Masa N.4 (H)',
    units: '1 Unidad',
    description: 'Masa número 4 especial',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.10,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n3',
    name: 'Masa N.3',
    units: '1 Unidad',
    description: 'Masa número 3',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.50,
    wholesale_price_usd: 1.25,
    price_cop: 3500,
    wholesale_price_cop: 3000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n1',
    name: 'Masa N.1',
    units: '1 Unidad',
    description: 'Masa número 1',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.24,
    wholesale_price_usd: 3.24,
    price_cop: 7500,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-pizza',
    name: 'Masa para Pizza',
    units: '5 Unidades',
    description: 'Pack de masas para pizza artesanal',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 5.22,
    wholesale_price_usd: 4.95,
    price_cop: 10500,
    wholesale_price_cop: 10500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── CAFETÍN Y COMIDA RÁPIDA ──────────────────────────────
  {
    id: 'cafetin-pasticho',
    name: 'Pasticho',
    units: '1 Plato',
    description: 'Pasticho casero',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 4.15,
    wholesale_price_usd: 4.15,
    price_cop: 15000,
    wholesale_price_cop: 15000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'cafetin-hamburguesa',
    name: 'Hamburguesa El Rellenito',
    units: '1 Unidad',
    description: 'Hamburguesa de la casa',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 3.85,
    wholesale_price_usd: 3.85,
    price_cop: 14000,
    wholesale_price_cop: 14000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetin-pizza-personal',
    name: 'Pizza Personal / Cruda',
    units: '1 Unidad',
    description: 'Pizza personal, lista o cruda',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetin-adicional-pollo',
    name: 'Adicional de Pollo',
    units: '1 Porción',
    description: 'Porción adicional de pollo',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 0.55,
    wholesale_price_usd: 0.55,
    price_cop: 2000,
    wholesale_price_cop: 2000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetin-empanadas-3',
    name: 'Empanadas Combo',
    units: '3 Unidades',
    description: 'Combo de 3 empanadas',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 1.10,
    wholesale_price_usd: 1.10,
    price_cop: 4000,
    wholesale_price_cop: 4000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetin-empanadas-2',
    name: 'Empanadas Combo',
    units: '2 Unidades',
    description: 'Combo de 2 empanadas',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 0.70,
    wholesale_price_usd: 0.70,
    price_cop: 2500,
    wholesale_price_cop: 2500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetin-pastelitos',
    name: 'Pastelitos Individuales',
    units: '1 Unidad',
    description: 'Pastelito individual',
    category: 'CAFETÍN',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── PANADERÍA Y REPOSTERÍA ───────────────────────────────
  {
    id: 'pan-canilla',
    name: 'Pan Canilla',
    units: '1 Unidad',
    description: 'Pan canilla artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 0.93,
    wholesale_price_usd: 0.93,
    price_cop: 2000,
    wholesale_price_cop: 2000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-espanol',
    name: 'Pan Español',
    units: '10 Unidades',
    description: 'Pan español',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 5000,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-dulce',
    name: 'Pan Dulce',
    units: '1 Unidad',
    description: 'Pan dulce artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.97,
    wholesale_price_usd: 2.97,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-perro-21',
    name: 'Pan de Perro',
    units: '21 Unidades',
    description: 'Pan para perro caliente',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'pan-perro-12',
    name: 'Pan de Perro',
    units: '12 Unidades',
    description: 'Pan para perro caliente',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 6000,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-perro-mini',
    name: 'Pan de Perro Mini',
    units: '10 Unidades',
    description: 'Pan para perro caliente mini',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 6000,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-hamb-tradicional',
    name: 'Pan Hamburguesa Tradicional',
    units: '10 Unidades',
    description: 'Pan para hamburguesa tradicional',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-wopper',
    name: 'Pan Wopper',
    units: '10 Unidades',
    description: 'Pan estilo wopper',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-hamb-mini',
    name: 'Pan Hamburguesa Mini Tradicional',
    units: '10 Unidades',
    description: 'Pan para hamburguesa mini',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    price_cop: 6000,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-cc',
    name: 'Pan Sandwich C/C',
    units: '1 Bolsa',
    description: 'Pan de sandwich con corteza',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.79,
    wholesale_price_usd: 2.79,
    price_cop: 6500,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-sc',
    name: 'Pan Sandwich S/C',
    units: '1 Bolsa',
    description: 'Pan de sandwich sin corteza',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.00,
    wholesale_price_usd: 3.00,
    price_cop: 7000,
    wholesale_price_cop: 6500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-vegano',
    name: 'Pan Vegano',
    units: '1 Bolsa',
    description: 'Pan artesanal vegano',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 4.29,
    wholesale_price_usd: 4.29,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-briochet',
    name: 'Pan Briochet',
    units: '6 Unidades',
    description: 'Pan briochet',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.00,
    wholesale_price_usd: 3.00,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-banquete-21',
    name: 'Pan de Banquete',
    units: '21 Unidades',
    description: 'Pan de banquete',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-tostado-salado',
    name: 'Pan Tostado Salado',
    units: '1 Unidad',
    description: 'Pan tostado sabor salado',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.74,
    wholesale_price_usd: 1.74,
    price_cop: 3000,
    wholesale_price_cop: 3000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-tostado-dulce',
    name: 'Pan Tostado Dulce',
    units: '1 Unidad',
    description: 'Pan tostado sabor dulce',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 5000,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'galletas-pasta-seca',
    name: 'Galletas Pasta Seca',
    units: '1 Paquete',
    description: 'Galletas de pasta seca',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.79,
    wholesale_price_usd: 2.79,
    price_cop: 6500,
    wholesale_price_cop: 6500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'palmeritas',
    name: 'Palmeritas',
    units: '10 Unidades',
    description: 'Palmeritas',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 5000,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mantecada',
    name: 'Mantecada',
    units: '1 Unidad',
    description: 'Mantecada (pequeña o grande)',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    price_cop: 6000,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'brazo-gitano',
    name: 'Brazo Gitano',
    units: '1 Unidad',
    description: 'Brazo gitano',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 4000,
    wholesale_price_cop: 4000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'brazo-reina',
    name: 'Brazo Reina',
    units: '1 Unidad',
    description: 'Brazo reina',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.29,
    wholesale_price_usd: 1.29,
    price_cop: 3000,
    wholesale_price_cop: 3000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'trifles',
    name: 'Trifles',
    units: '1 Unidad',
    description: 'Postre trifles',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 6000,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'quesillo',
    name: 'Quesillo',
    units: '1 Unidad',
    description: 'Quesillo venezolano',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    price_cop: 6000,
    wholesale_price_cop: 6000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-tres-leche',
    name: 'Torta Tres Leche',
    units: '1 Unidad',
    description: 'Torta tres leches',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'repollitas',
    name: 'Repollitas',
    units: '20 Unidades',
    description: 'Repollitas',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-1kg',
    name: 'Torta 1 Kg',
    units: '1 KG',
    description: 'Torta de 1 kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 17.19,
    wholesale_price_usd: 17.19,
    price_cop: 40000,
    wholesale_price_cop: 40000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-medio-kg',
    name: 'Torta 1/2 Kg',
    units: '1/2 KG',
    description: 'Torta de medio kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 12.90,
    wholesale_price_usd: 12.90,
    price_cop: 30000,
    wholesale_price_cop: 30000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-cuarto-kg',
    name: 'Torta 1/4 Kg',
    units: '1/4 KG',
    description: 'Torta de cuarto de kilo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 8.61,
    wholesale_price_usd: 8.61,
    price_cop: 20000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'combo-torta-1kg',
    name: 'Combo Torta 1 Kg',
    units: '1 KG',
    description: 'Combo de torta de 1 kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 15.00,
    wholesale_price_usd: 15.00,
    price_cop: 57000,
    wholesale_price_cop: 57000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cascaritas',
    name: 'Cascaritas',
    units: '1 Paquete',
    description: 'Cascaritas',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    price_cop: 5000,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'biscocho-1kg',
    name: 'Biscocho 1 Kg',
    units: '1 KG',
    description: 'Biscocho de 1 kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 6.81,
    wholesale_price_usd: 6.81,
    price_cop: 20000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'biscocho-medio-kg',
    name: 'Biscocho 1/2 Kg',
    units: '1/2 KG',
    description: 'Biscocho de medio kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    price_cop: 15000,
    wholesale_price_cop: 15000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'biscocho-cuarto-kg',
    name: 'Biscocho 1/4 Kg',
    units: '1/4 KG',
    description: 'Biscocho de cuarto de kilo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 4.30,
    wholesale_price_usd: 4.30,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'trufas',
    name: 'Trufas',
    units: '1 Unidad',
    description: 'Trufas de chocolate',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.08,
    wholesale_price_usd: 1.08,
    price_cop: 2500,
    wholesale_price_cop: 2500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'brownie',
    name: 'Brownie',
    units: '1 Unidad',
    description: 'Brownie',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.02,
    wholesale_price_usd: 3.02,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-milhoja',
    name: 'Torta Milhoja',
    units: '1 Unidad',
    description: 'Torta milhoja',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.44,
    wholesale_price_usd: 2.44,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'gelatinas',
    name: 'Gelatinas Sabores',
    units: '1 Vaso',
    description: 'Gelatina en varios sabores',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.16,
    wholesale_price_usd: 1.16,
    price_cop: 3000,
    wholesale_price_cop: 3000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── SALSAS Y COMPLEMENTOS ────────────────────────────────
  {
    id: 'mayonesa-original',
    name: 'Mayonesa Original',
    units: '1 Galón / Frasco',
    description: 'Mayonesa artesanal original',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 8.53,
    wholesale_price_usd: 7.74,
    price_cop: 23000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'mayonesa-premium',
    name: 'Mayonesa Premium',
    units: '1 Galón / Frasco',
    description: 'Mayonesa artesanal premium',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 19.66,
    wholesale_price_usd: 19.66,
    price_cop: 53000,
    wholesale_price_cop: 53000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayonesa-rindemax',
    name: 'Mayonesa Rindemax',
    units: '1 Galón / Frasco',
    description: 'Mayonesa Rindemax',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 7.74,
    wholesale_price_usd: 7.74,
    price_cop: 23000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-bbq',
    name: 'Salsa B.B.Q',
    units: '1 Galón / Frasco',
    description: 'Salsa barbecue',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    price_cop: 23000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-cheddar',
    name: 'Salsa Cheddar',
    units: '1 Galón / Frasco',
    description: 'Salsa cheddar',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    price_cop: 23000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-mostaza',
    name: 'Salsa Mostaza',
    units: '1 Galón / Frasco',
    description: 'Salsa de mostaza',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    price_cop: 23000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-ketchup',
    name: 'Salsa Ketchup',
    units: '1 Galón / Frasco',
    description: 'Salsa ketchup',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    price_cop: 23000,
    wholesale_price_cop: 20000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-sabores-prep',
    name: 'Salsa Sabores Preparados',
    units: '1 Galón / Frasco',
    description: 'Salsa con sabores preparados',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 2.44,
    wholesale_price_usd: 2.44,
    price_cop: 7000,
    wholesale_price_cop: 7000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── BEBIDAS Y LÍQUIDOS ───────────────────────────────────
  {
    id: 'coca-1lt',
    name: 'Coca Cola 1 Lt',
    units: '1 LT',
    description: 'Coca Cola 1 litro',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.74,
    wholesale_price_usd: 1.74,
    price_cop: 5500,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'coca-2lt',
    name: 'Coca Cola 2 Lt',
    units: '2 LT',
    description: 'Coca Cola 2 litros',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 2.37,
    wholesale_price_usd: 2.37,
    price_cop: 6000,
    wholesale_price_cop: 5500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'coca-15lt',
    name: 'Coca Cola 1.5 Lt',
    units: '1.5 LT',
    description: 'Coca Cola 1.5 litros',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    price_cop: 5500,
    wholesale_price_cop: 5000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'coca-355',
    name: 'Coca Cola 355 ml',
    units: '355 ML',
    description: 'Coca Cola lata 355 ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.08,
    wholesale_price_usd: 1.08,
    price_cop: 2500,
    wholesale_price_cop: 2500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'agua-355',
    name: 'Agua 355 ml',
    units: '355 ML',
    description: 'Agua mineral 355 ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.08,
    wholesale_price_usd: 1.08,
    price_cop: 1500,
    wholesale_price_cop: 1500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'agua-600',
    name: 'Agua 600 ml',
    units: '600 ML',
    description: 'Agua mineral 600 ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.50,
    wholesale_price_usd: 1.50,
    price_cop: 2500,
    wholesale_price_cop: 2500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'agua-5lt',
    name: 'Agua 5 Lt',
    units: '5 LT',
    description: 'Agua mineral 5 litros',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    price_cop: 4500,
    wholesale_price_cop: 3500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'jugo-valle-500',
    name: 'Jugo del Valle 500 ml',
    units: '500 ML',
    description: 'Jugo del Valle 500 ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.29,
    wholesale_price_usd: 1.29,
    price_cop: 4500,
    wholesale_price_cop: 3500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'jugo-valle-1lt',
    name: 'Jugo del Valle 1 Lt',
    units: '1 LT',
    description: 'Jugo del Valle 1 litro',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    price_cop: 4500,
    wholesale_price_cop: 4500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'bebidas-malta-masato',
    name: 'Malta Maxi / Masato / Jugos',
    units: '1 Unidad',
    description: 'Malta Maxi, masato o jugos',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 0.70,
    wholesale_price_usd: 0.70,
    price_cop: 2500,
    wholesale_price_cop: 2500,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'merengadas',
    name: 'Merengadas',
    units: '1 Vaso',
    description: 'Merengada artesanal',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 2.50,
    wholesale_price_usd: 2.50,
    price_cop: 9000,
    wholesale_price_cop: 9000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },

  // ─── POSTRES ──────────────────────────────────────────────
  // Porciones individuales del catálogo anterior (precios previos en USD;
  // el COP se deriva de USD × tasa, como estaban antes).
  {
    id: 'postres-torta-grande',
    name: 'Porción Torta Grande',
    units: '1 Porción',
    description: 'Porción grande de torta artesanal',
    category: 'POSTRES',
    type: 'ambos',
    price_usd: 0.95,
    wholesale_price_usd: 0.95,
    price_cop: null,
    wholesale_price_cop: null,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-torta-mediana',
    name: 'Porción Torta Mediana',
    units: '1 Porción',
    description: 'Porción mediana de torta artesanal',
    category: 'POSTRES',
    type: 'ambos',
    price_usd: 0.83,
    wholesale_price_usd: 0.83,
    price_cop: null,
    wholesale_price_cop: null,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-torta-pequeña',
    name: 'Porción Torta Pequeña',
    units: '1 Porción',
    description: 'Porción pequeña de torta artesanal',
    category: 'POSTRES',
    type: 'ambos',
    price_usd: 0.48,
    wholesale_price_usd: 0.48,
    price_cop: null,
    wholesale_price_cop: null,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-mantecada',
    name: 'Porción Mantecada',
    units: '1 Porción',
    description: 'Porción de mantecada artesanal',
    category: 'POSTRES',
    type: 'ambos',
    price_usd: 0.71,
    wholesale_price_usd: 0.71,
    price_cop: null,
    wholesale_price_cop: null,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-trufa-grande',
    name: 'Trufa Grande',
    units: '1 Unidad',
    description: 'Trufa de chocolate artesanal grande',
    category: 'POSTRES',
    type: 'ambos',
    price_usd: 0.60,
    wholesale_price_usd: 0.60,
    price_cop: null,
    wholesale_price_cop: null,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-pan-de-dios',
    name: 'Pan de Dios',
    units: '1 Unidad',
    description: 'Pan de Dios artesanal',
    category: 'POSTRES',
    type: 'ambos',
    price_usd: 1.19,
    wholesale_price_usd: 1.19,
    price_cop: null,
    wholesale_price_cop: null,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── COMBOS ESPECIALES ────────────────────────────────────
  {
    id: 'combo-cumpleanero',
    name: 'Combo Cumpleañero',
    units: '1 Combo',
    description: 'Combo especial de cumpleaños',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 23.00,
    wholesale_price_usd: 23.00,
    price_cop: 64000,
    wholesale_price_cop: 64000,
    available: true,
    image_url: null,
    is_best_seller: true,
  },

  // ─── COMBOS DE EVENTO ─────────────────────────────────────
  // Precio fijo (sin personalización). USD derivado del COP (~3500) — editable
  // en el panel. El servicio de fritos va incluido a $0 en el precio del combo.
  {
    id: 'combo-evento-1',
    name: 'Combo 1 (Pequeño)',
    units: '1 Combo',
    description: '1 Torta 1 Kilo, 1 Bandeja Galletas, 1 Gelatina, 1 Coca-Cola 2L',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 16.29,
    wholesale_price_usd: 16.29,
    price_cop: 57000,
    wholesale_price_cop: 57000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'combo-evento-2',
    name: 'Combo 2 (Pequeño)',
    units: '1 Combo',
    description: '1 Torta 1 Kilo, 1 Bandeja Palmeritas, 1 Porción Repollitas. Incluye selección: 25 Tequeños Mini o 15 Pastelitos (indicar al pedir)',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 19.43,
    wholesale_price_usd: 19.43,
    price_cop: 68000,
    wholesale_price_cop: 68000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'combo-evento-3',
    name: 'Combo 3 (~50 personas)',
    units: '1 Combo',
    description: '4 Bandejas Tequeños (100u), 7 Bandejas Pasapalos (100u), 2 Bandeja Morcilla (50u), 2 Bandejas Bolitas de Carne (30u)',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 36.00,
    wholesale_price_usd: 36.00,
    price_cop: 126000,
    wholesale_price_cop: 126000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'combo-evento-4',
    name: 'Combo 4 (~70 personas)',
    units: '1 Combo',
    description: '4 Bandejas Tequeños (100u), 5 Bandejas Pasapalos (75u), 2 Pasapalos Carne (30u), 2 Pasapalos Pollo (30u), 2 Bandejas Hallaquita (50u), 2 Morcilla (50u), 2 Bolitas Carne (30u)',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 64.00,
    wholesale_price_usd: 64.00,
    price_cop: 224000,
    wholesale_price_cop: 224000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'combo-evento-5',
    name: 'Combo 5 (~150 personas)',
    units: '1 Combo',
    description: '12 Combos Tequeños (300u), 10 Pasapalos (150u), 4 Bandejas Morcilla (100u), 4 Bandejas Bolitas Carne (60u), 1 Combo Mini Pizzas (20u), 4 Bandejas Hallaquita (100u)',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 114.86,
    wholesale_price_usd: 114.86,
    price_cop: 402000,
    wholesale_price_cop: 402000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'combo-evento-6',
    name: 'Combo 6 (~25 personas)',
    units: '1 Combo',
    description: '1 Combo Mini Pizzas (20u), 2 Tequeños (50u), 3 Pastelitos (45u), 1 Coca-Cola 2L',
    category: 'COMBOS',
    type: 'ambos',
    price_usd: 27.43,
    wholesale_price_usd: 27.43,
    price_cop: 96000,
    wholesale_price_cop: 96000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── PIZZERÍA ─────────────────────────────────────────────
  // Menú de pizzas. Precio en COP nativo; USD derivado (~3500), editable.
  {
    id: 'pizza-clasica',
    name: 'Clásica',
    units: '1 Pizza',
    description: 'Queso, chorizo, maíz, tocineta, pimentón, salsa de tomate',
    category: 'PIZZERIA',
    type: 'ambos',
    price_usd: 2.29,
    wholesale_price_usd: 2.29,
    price_cop: 8000,
    wholesale_price_cop: 8000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pizza-pepperoni',
    name: 'Pepperoni',
    units: '1 Pizza',
    description: 'Queso, pepperoni, anchoas, cebolla, pimentón, salsa de tomate',
    category: 'PIZZERIA',
    type: 'ambos',
    price_usd: 2.86,
    wholesale_price_usd: 2.86,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pizza-hawaiana',
    name: 'Hawaiana',
    units: '1 Pizza',
    description: 'Queso, piña, bocadillo, salsa de tomate',
    category: 'PIZZERIA',
    type: 'ambos',
    price_usd: 2.86,
    wholesale_price_usd: 2.86,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pizza-salami',
    name: 'Salami',
    units: '1 Pizza',
    description: 'Queso, salami, anchoas, cebolla, pimentón, salsa de tomate',
    category: 'PIZZERIA',
    type: 'ambos',
    price_usd: 2.86,
    wholesale_price_usd: 2.86,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pizza-infantil',
    name: 'Infantil',
    units: '1 Pizza',
    description: 'Queso, pollo, jamón, salsa de tomate',
    category: 'PIZZERIA',
    type: 'ambos',
    price_usd: 2.86,
    wholesale_price_usd: 2.86,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pizza-de-la-casa',
    name: 'De la casa',
    units: '1 Pizza',
    description: 'Tocineta, pollo, anchoas, salami, cebolla, pimentón, salsa de tomate',
    category: 'PIZZERIA',
    type: 'ambos',
    price_usd: 2.86,
    wholesale_price_usd: 2.86,
    price_cop: 10000,
    wholesale_price_cop: 10000,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
];

export const categories: ProductCategory[] = [
  'TEQUEÑOS',
  'PASAPALOS',
  'MASAS',
  'CAFETÍN',
  'PANADERIA',
  'SALSAS',
  'BEBIDAS',
  'POSTRES',
  'PIZZERIA',
  'COMBOS',
];

export const categoryLabels: Record<ProductCategory, string> = {
  'TEQUEÑOS': 'Tequeños',
  PASAPALOS: 'Pasapalos',
  MASAS: 'Masas',
  PANADERIA: 'Panadería',
  'CAFETÍN': 'Cafetín',
  SALSAS: 'Salsas',
  BEBIDAS: 'Bebidas',
  POSTRES: 'Postres',
  PIZZERIA: 'Pizzería',
  COMBOS: 'Combos',
};

/** Emoji por categoría — fuente única (carrito, upsell, tarjetas…). */
export const categoryEmoji: Record<ProductCategory, string> = {
  'TEQUEÑOS': '🧀',
  PASAPALOS: '🍢',
  MASAS: '🥖',
  PANADERIA: '🥐',
  'CAFETÍN': '🍔',
  SALSAS: '🫙',
  BEBIDAS: '🥤',
  POSTRES: '🎂',
  PIZZERIA: '',
  COMBOS: '🎁',
};
