export type ProductCategory =
  | 'TEQUEÑOS'
  | 'PASAPALOS'
  | 'MASAS'
  | 'PANADERIA'
  | 'CAFETÍN'
  | 'SALSAS'
  | 'BEBIDAS'
  | 'POSTRES'
  | 'COMBOS';

export type ProductType = 'detal' | 'mayorista' | 'ambos';

export interface Product {
  id: string;
  name: string;
  /** Subtítulo de unidades, ej. "25 unidades", "1 kg", "Pack x10". Opcional. */
  units?: string | null;
  description: string;
  category: ProductCategory;
  type: ProductType;
  price_usd: number;
  wholesale_price_usd: number;
  available: boolean;
  image_url: string | null;
  is_best_seller: boolean;
}

export const products: Product[] = [

  // ─── TEQUEÑOS ─────────────────────────────────────────────
  // Catálogo original del cliente — precios retail por pack
  {
    id: 'tequeno-super-queso',
    name: 'Tequeño Super Queso',
    description: 'Tequeño súper relleno de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 9.00,
    wholesale_price_usd: 9.00,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'tequeno-super-byq',
    name: 'Tequeño Super B y Q',
    description: 'Tequeño súper bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 9.90,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-tyq',
    name: 'Tequeño T y Q',
    description: 'Tequeño tocineta y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 10.00,
    wholesale_price_usd: 10.00,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-tradicional-queso-25',
    name: 'Tequeño Tradicional Queso — 25 und',
    description: '25 unidades de tequeño tradicional de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 5.85,
    wholesale_price_usd: 5.85,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'tequeno-tradicional-byq',
    name: 'Tequeño Tradicional B y Q',
    description: 'Tequeño tradicional bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.32,
    wholesale_price_usd: 7.32,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-escolar-queso',
    name: 'Tequeño Escolar Queso',
    description: 'Tequeño tamaño escolar de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.12,
    wholesale_price_usd: 6.12,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-escolar-byq',
    name: 'Tequeño Escolar B y Q',
    description: 'Tequeño escolar bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-doble-queso',
    name: 'Tequeño Doble Queso',
    description: 'Tequeño con doble relleno de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.74,
    wholesale_price_usd: 6.88,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'tequeno-doble-surtido',
    name: 'Tequeño Doble Surtido',
    description: 'Tequeño doble con rellenos variados',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 8.61,
    wholesale_price_usd: 8.61,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-mini-25-combo',
    name: 'Tequeño Mini — 25 und Combo',
    description: 'Combo de 25 tequeños mini',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 2.94,
    wholesale_price_usd: 2.79,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-queso',
    name: 'Tequeño Normal Queso',
    description: 'Tequeño tamaño normal de queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 6.43,
    wholesale_price_usd: 6.43,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-byq',
    name: 'Tequeño Normal B y Q',
    description: 'Tequeño normal bocadillo y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.11,
    wholesale_price_usd: 7.11,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-tyq',
    name: 'Tequeño Normal T y Q',
    description: 'Tequeño normal tocineta y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.13,
    wholesale_price_usd: 7.13,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'tequeno-normal-jyq',
    name: 'Tequeño Normal J y Q',
    description: 'Tequeño normal jamón y queso',
    category: 'TEQUEÑOS',
    type: 'ambos',
    price_usd: 7.11,
    wholesale_price_usd: 7.11,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── PASAPALOS ────────────────────────────────────────────
  // Productos originales del cliente
  {
    id: 'pasapalos-15-combo',
    name: 'Pasapalos — 15 und Combo',
    description: 'Combo de 15 pasapalos surtidos',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.22,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'pasapalos-pollo-carne',
    name: 'Pasapalos Pollo/Carne',
    description: 'Pasapalos de pollo o carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.16,
    wholesale_price_usd: 5.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'bolitas-carne-15',
    name: 'Bolitas de Carne — 15 und',
    description: '15 unidades de bolitas de carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.16,
    wholesale_price_usd: 5.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'morcillitas-25',
    name: 'Morcillitas — 25 und',
    description: '25 unidades de morcillitas',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pastelon-pizza-10',
    name: 'Pastelón Pizza — 10 und',
    description: '10 unidades de pastelón de pizza',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.16,
    wholesale_price_usd: 5.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pastelon-ac-10',
    name: 'Pastelón A/C — 10 und',
    description: '10 unidades de pastelón atún y carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 5.58,
    wholesale_price_usd: 5.58,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pastelon-pc-10',
    name: 'Pastelón P/C — 10 und',
    description: '10 unidades de pastelón pollo y carne',
    category: 'PASAPALOS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 9.90,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  // Nuevos del complemento (imágenes PDFs)
  {
    id: 'pasapalos-teq-qsb-25',
    name: 'Tequeñitos Q/S/B — 25 und',
    description: '25 tequeñitos de queso, sal o bocadillo',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 1.43,
    wholesale_price_usd: 1.43,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-teq-queso-relleno-25',
    name: 'Tequeñitos Queso + Relleno — 25 und',
    description: '25 tequeñitos de queso con relleno especial',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 2.62,
    wholesale_price_usd: 2.62,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-teq-byq-relleno-25',
    name: 'Tequeñitos Bocadillo + Queso + Relleno — 25 und',
    description: '25 tequeñitos de bocadillo, queso y relleno',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 3.10,
    wholesale_price_usd: 3.10,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-doble-queso-10',
    name: 'Doble Queso — 10 und',
    description: 'Tequeños doble relleno de queso, 10 unidades',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 3.33,
    wholesale_price_usd: 3.33,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'pasapalos-pizzas-mini-20',
    name: 'Pizzas Mini Básica — 20 und',
    description: '20 minipizzas básicas artesanales',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 7.14,
    wholesale_price_usd: 7.14,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-pastelitos-arrozcarne-15',
    name: 'Pastelitos Arroz con Carne — 15 und',
    description: '15 pastelitos rellenos de arroz con carne',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 1.67,
    wholesale_price_usd: 1.67,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-pastelitos-pizza-15',
    name: 'Pastelitos Pizza — 15 und',
    description: '15 pastelitos sabor pizza',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 1.67,
    wholesale_price_usd: 1.67,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-pastelitos-surtidos-15',
    name: 'Pastelitos Surtidos — 15 und',
    description: 'Pollo, carne, jamón+queso y bocadillo+queso',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 3.10,
    wholesale_price_usd: 3.10,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pasapalos-empanada',
    name: 'Empanada (Mixta/Pollo/Carne)',
    description: 'Unidad — mixta, de pollo o de carne',
    category: 'PASAPALOS',
    type: 'detal',
    price_usd: 0.95,
    wholesale_price_usd: 0.95,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── MASAS ────────────────────────────────────────────────
  // Productos originales del cliente
  {
    id: 'masa-1kg',
    name: 'Masa 1 Kg',
    description: 'Masa fácil artesanal 1 kilogramo',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.18,
    wholesale_price_usd: 3.00,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-750',
    name: 'Masa 750 g',
    description: 'Masa fácil artesanal 750 gramos',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 2.37,
    wholesale_price_usd: 2.15,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-500',
    name: 'Masa 500 g',
    description: 'Masa fácil artesanal 500 gramos',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.50,
    wholesale_price_usd: 1.29,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n4',
    name: 'Masa N.4',
    description: 'Masa número 4',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.18,
    wholesale_price_usd: 3.00,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n4-h',
    name: 'Masa N.4 (H)',
    description: 'Masa número 4 especial',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n3',
    name: 'Masa N.3',
    description: 'Masa número 3',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.50,
    wholesale_price_usd: 1.29,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-n1',
    name: 'Masa N.1',
    description: 'Masa número 1',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 3.24,
    wholesale_price_usd: 3.00,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  // Nuevos del complemento (imágenes PDFs) — presentaciones adicionales
  {
    id: 'masa-kilo-cuad-red',
    name: 'Masa Kilo (cuadrada/redonda)',
    description: 'Masa fácil artesanal 1 kg, disponible cuadrada o redonda',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.67,
    wholesale_price_usd: 1.55,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'masa-mediana',
    name: 'Masa Mediana',
    description: 'Masa fácil artesanal presentación mediana',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.19,
    wholesale_price_usd: 1.07,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-pequeña',
    name: 'Masa Pequeña',
    description: 'Masa fácil artesanal presentación pequeña',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 0.83,
    wholesale_price_usd: 0.60,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-par-hornear',
    name: 'Masa Par Hornear',
    description: 'Masa lista para hornear en casa',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 1.90,
    wholesale_price_usd: 1.79,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'masa-pizza-5',
    name: 'Masa para Pizzas — 5 und (23 cm)',
    description: 'Pack de 5 masas de pizza artesanal de 23 cm',
    category: 'MASAS',
    type: 'ambos',
    price_usd: 2.38,
    wholesale_price_usd: 2.38,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  // Tequeños al mayor (mayoristas)
  {
    id: 'mayor-super-queso-10',
    name: 'Súper de Queso Al Mayor — 10 und',
    description: 'Tequeño súper tamaño, relleno de queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 4.76,
    wholesale_price_usd: 4.76,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-super-byq-10',
    name: 'Súper Bocadillo y Queso Al Mayor — 10 und',
    description: 'Tequeño súper con bocadillo y queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 5.24,
    wholesale_price_usd: 5.24,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-super-doblequeso-10',
    name: 'Súper Doble Queso Al Mayor — 10 und',
    description: 'Tequeño súper doble relleno de queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 5.71,
    wholesale_price_usd: 5.71,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-super-doblebyq-10',
    name: 'Súper Doble Bocadillo y Queso Al Mayor — 10 und',
    description: 'Tequeño súper doble bocadillo y queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 6.19,
    wholesale_price_usd: 6.19,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-escolar-queso-10',
    name: 'Escolar Queso Al Mayor — 10 und',
    description: 'Tequeño escolar relleno de queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 2.62,
    wholesale_price_usd: 2.62,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-escolar-byq-10',
    name: 'Escolar Bocadillo y Queso Al Mayor — 10 und',
    description: 'Tequeño escolar bocadillo y queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 3.10,
    wholesale_price_usd: 3.10,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-escolar-doblequeso-10',
    name: 'Escolar Doble Queso Al Mayor — 10 und',
    description: 'Tequeño escolar doble relleno de queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 3.33,
    wholesale_price_usd: 3.33,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayor-escolar-doblebyq-10',
    name: 'Escolar Doble Bocadillo y Queso Al Mayor — 10 und',
    description: 'Tequeño escolar doble bocadillo y queso · precio al mayor',
    category: 'MASAS',
    type: 'mayorista',
    price_usd: 4.29,
    wholesale_price_usd: 4.29,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── PANADERÍA ───────────────────────────────────────────
  // Catálogo completo original del cliente
  {
    id: 'pan-canilla',
    name: 'Pan Canilla',
    description: 'Pan canilla artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 0.93,
    wholesale_price_usd: 0.93,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-espanol-10',
    name: 'Pan Español — 10 und',
    description: '10 unidades de pan español',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-dulce',
    name: 'Pan Dulce',
    description: 'Pan dulce artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.97,
    wholesale_price_usd: 2.97,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-perro-21',
    name: 'Pan de Perro — 21 und',
    description: '21 unidades de pan para perro caliente',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'pan-perro-12',
    name: 'Pan de Perro — 12 und',
    description: '12 unidades de pan para perro caliente',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-perro-mini-10',
    name: 'Pan de Perro Mini — 10 und',
    description: '10 unidades de pan para perro mini',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-hamburguesa-trad',
    name: 'Pan Hamburguesa Tradicional',
    description: 'Pan para hamburguesa tradicional',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-whopper',
    name: 'Pan Whopper',
    description: 'Pan estilo whopper',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-hamburguesa-mini',
    name: 'Pan Hamburguesa Mini',
    description: 'Pan para hamburguesa mini',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-cc',
    name: 'Pan Sandwich C/C',
    description: 'Pan de sandwich con corteza',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.79,
    wholesale_price_usd: 2.58,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-sc',
    name: 'Pan Sandwich S/C',
    description: 'Pan de sandwich sin corteza',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.00,
    wholesale_price_usd: 2.79,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-integral',
    name: 'Pan Sandwich Integral',
    description: 'Pan de sandwich integral',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 4.45,
    wholesale_price_usd: 4.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-vegano',
    name: 'Pan Vegano',
    description: 'Pan artesanal vegano',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 4.29,
    wholesale_price_usd: 4.29,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-briochet-6',
    name: 'Pan Briochet — 6 und',
    description: '6 unidades de pan briochet',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.00,
    wholesale_price_usd: 3.00,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-banquete-21',
    name: 'Pan de Banquete — 21 und',
    description: '21 unidades de pan de banquete',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-tostado-salado',
    name: 'Pan Tostado Salado',
    description: 'Pan tostado sabor salado',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.74,
    wholesale_price_usd: 1.74,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-tostado-dulce',
    name: 'Pan Tostado Dulce',
    description: 'Pan tostado sabor dulce',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'galletas-pasta-seca',
    name: 'Galletas Pasta Seca',
    description: 'Galletas de pasta seca artesanales',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.79,
    wholesale_price_usd: 2.79,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'palmeritas-10',
    name: 'Palmeritas — 10 und',
    description: '10 unidades de palmeritas',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mantecada-pona',
    name: 'Mantecada Poña',
    description: 'Mantecada artesanal pequeña',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mantecada-grande',
    name: 'Mantecada Grande',
    description: 'Mantecada artesanal grande',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'brazo-gitano',
    name: 'Brazo Gitano',
    description: 'Brazo gitano artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'brazo-reina',
    name: 'Brazo Reina',
    description: 'Brazo reina artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.29,
    wholesale_price_usd: 1.29,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'trifles',
    name: 'Trifles',
    description: 'Postre trifles artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'quesillo',
    name: 'Quesillo',
    description: 'Quesillo venezolano artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.58,
    wholesale_price_usd: 2.58,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-tres-leches',
    name: 'Torta Tres Leches',
    description: 'Torta tres leches artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'repollitas-20',
    name: 'Repollitas — 20 und',
    description: '20 unidades de repollitas',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.45,
    wholesale_price_usd: 3.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-1kg',
    name: 'Torta 1 Kg',
    description: 'Torta artesanal de 1 kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 17.19,
    wholesale_price_usd: 17.19,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-media',
    name: 'Torta 1/2',
    description: 'Torta artesanal media',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 12.90,
    wholesale_price_usd: 12.90,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-cuarto',
    name: 'Torta 1/4',
    description: 'Torta artesanal cuarto',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 8.61,
    wholesale_price_usd: 8.61,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-1kg-combo',
    name: 'Torta 1 Kg Combo',
    description: 'Combo torta 1 Kg con decoración',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 24.54,
    wholesale_price_usd: 24.54,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cascaritas',
    name: 'Cascaritas',
    description: 'Cascaritas artesanales',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.16,
    wholesale_price_usd: 2.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'biscocho-1kg',
    name: 'Biscocho 1 Kg',
    description: 'Biscocho artesanal 1 kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 6.81,
    wholesale_price_usd: 6.81,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'biscocho-medio',
    name: 'Biscocho 1/2 Kg',
    description: 'Biscocho artesanal medio kilogramo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 6.45,
    wholesale_price_usd: 6.45,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'biscocho-cuarto',
    name: 'Biscocho 1/4 Kg',
    description: 'Biscocho artesanal cuarto de kilo',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 4.30,
    wholesale_price_usd: 4.30,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'trufas',
    name: 'Trufas',
    description: 'Trufas de chocolate artesanales',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.08,
    wholesale_price_usd: 1.08,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'brownie',
    name: 'Brownie',
    description: 'Brownie artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 3.02,
    wholesale_price_usd: 3.02,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'torta-milhoja',
    name: 'Torta Milhoja',
    description: 'Torta milhoja artesanal',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 2.44,
    wholesale_price_usd: 2.44,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'gelatinas',
    name: 'Gelatinas Sabores',
    description: 'Gelatinas en varios sabores',
    category: 'PANADERIA',
    type: 'ambos',
    price_usd: 1.16,
    wholesale_price_usd: 1.16,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  // Sandwiches nuevos del complemento (no estaban en el original)
  {
    id: 'pan-sandwich-integral-grande',
    name: 'Sandwich Integral Grande',
    description: 'Pan sandwich integral artesanal grande',
    category: 'PANADERIA',
    type: 'detal',
    price_usd: 2.38,
    wholesale_price_usd: 2.38,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-integral-pequeño',
    name: 'Sandwich Integral Pequeño',
    description: 'Pan sandwich integral artesanal pequeño',
    category: 'PANADERIA',
    type: 'detal',
    price_usd: 1.90,
    wholesale_price_usd: 1.90,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-normal-grande',
    name: 'Sandwich Normal Grande',
    description: 'Pan sandwich normal artesanal grande',
    category: 'PANADERIA',
    type: 'detal',
    price_usd: 1.90,
    wholesale_price_usd: 1.90,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-normal-pequeño',
    name: 'Sandwich Normal Pequeño',
    description: 'Pan sandwich normal artesanal pequeño',
    category: 'PANADERIA',
    type: 'detal',
    price_usd: 1.43,
    wholesale_price_usd: 1.43,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'pan-sandwich-multicereales',
    name: 'Sandwich Multicereales',
    description: 'Pan sandwich artesanal multicereales',
    category: 'PANADERIA',
    type: 'detal',
    price_usd: 2.38,
    wholesale_price_usd: 2.38,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── CAFETÍN (nuevo del complemento) ─────────────────────
  {
    id: 'cafetín-pasticho',
    name: 'Pasticho',
    description: 'Porción de pasticho casero',
    category: 'CAFETÍN',
    type: 'detal',
    price_usd: 3.57,
    wholesale_price_usd: 3.57,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetín-hamburguesa',
    name: 'Hamburguesa + Nestea',
    description: 'Hamburguesa en pan de ajillo con Nestea incluido',
    category: 'CAFETÍN',
    type: 'detal',
    price_usd: 3.33,
    wholesale_price_usd: 3.33,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetín-pizza-personal',
    name: 'Pizza Personal + Nestea',
    description: 'Pizza personal artesanal con Nestea incluido',
    category: 'CAFETÍN',
    type: 'detal',
    price_usd: 1.67,
    wholesale_price_usd: 1.67,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'cafetín-perro-caliente',
    name: 'Perro Caliente',
    description: 'No disponible por el momento',
    category: 'CAFETÍN',
    type: 'detal',
    price_usd: 0,
    wholesale_price_usd: 0,
    available: false,
    image_url: null,
    is_best_seller: false,
  },

  // ─── SALSAS ───────────────────────────────────────────────
  // Catálogo original del cliente
  {
    id: 'mayonesa-original',
    name: 'Mayonesa Original',
    description: 'Mayonesa artesanal original',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 8.53,
    wholesale_price_usd: 7.74,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'mayonesa-premium',
    name: 'Mayonesa Premium',
    description: 'Mayonesa artesanal premium',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 19.66,
    wholesale_price_usd: 19.66,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'mayonesa-rindemax',
    name: 'Mayonesa Rindemax',
    description: 'Mayonesa Rindemax artesanal',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 7.74,
    wholesale_price_usd: 7.74,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-bbq',
    name: 'Salsa B.B.Q',
    description: 'Salsa barbecue artesanal',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-cheddar',
    name: 'Salsa Cheddar',
    description: 'Salsa cheddar artesanal',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-mostaza',
    name: 'Salsa Mostaza',
    description: 'Salsa de mostaza artesanal',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 7.74,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-ketchup',
    name: 'Salsa Ketchup',
    description: 'Salsa ketchup artesanal',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 9.90,
    wholesale_price_usd: 9.90,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'salsa-sabores-preparados',
    name: 'Salsa Sabores Preparados',
    description: 'Salsa con sabores especiales preparados',
    category: 'SALSAS',
    type: 'ambos',
    price_usd: 2.44,
    wholesale_price_usd: 2.44,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── BEBIDAS ──────────────────────────────────────────────
  // Bebidas originales del cliente (comerciales)
  {
    id: 'coca-1lt',
    name: 'Coca Cola 1 Lt',
    description: 'Coca Cola 1 litro',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.74,
    wholesale_price_usd: 1.50,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'coca-2lt',
    name: 'Coca Cola 2 Lt',
    description: 'Coca Cola 2 litros',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 2.37,
    wholesale_price_usd: 2.15,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'coca-15lt',
    name: 'Coca Cola 1½ Lt',
    description: 'Coca Cola 1.5 litros',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'coca-355',
    name: 'Coca Cola 355 ml',
    description: 'Coca Cola lata 355ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.08,
    wholesale_price_usd: 1.08,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'agua-355',
    name: 'Agua 355 ml',
    description: 'Agua mineral 355ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.08,
    wholesale_price_usd: 1.08,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'agua-600',
    name: 'Agua 600 ml',
    description: 'Agua mineral 600ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.50,
    wholesale_price_usd: 1.50,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'agua-5lt',
    name: 'Agua 5 Lt',
    description: 'Agua mineral 5 litros',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.50,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'jugo-valle-500',
    name: 'Jugo del Valle 500 ml',
    description: 'Jugo del Valle 500ml',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.29,
    wholesale_price_usd: 1.29,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'jugo-valle-1lt',
    name: 'Jugo del Valle 1 Lt',
    description: 'Jugo del Valle 1 litro',
    category: 'BEBIDAS',
    type: 'ambos',
    price_usd: 1.95,
    wholesale_price_usd: 1.95,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  // Bebidas artesanales nuevas del complemento
  {
    id: 'bebidas-merengada',
    name: 'Merengada',
    description: 'Fresa, mora, mango o guanábana',
    category: 'BEBIDAS',
    type: 'detal',
    price_usd: 2.14,
    wholesale_price_usd: 2.14,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
  {
    id: 'bebidas-malta',
    name: 'Malta',
    description: 'Malta fría',
    category: 'BEBIDAS',
    type: 'detal',
    price_usd: 0.71,
    wholesale_price_usd: 0.71,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'bebidas-maxi',
    name: 'Maxi',
    description: 'Bebida Maxi',
    category: 'BEBIDAS',
    type: 'detal',
    price_usd: 0.48,
    wholesale_price_usd: 0.48,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'bebidas-masato',
    name: 'Masato',
    description: 'Masato artesanal',
    category: 'BEBIDAS',
    type: 'detal',
    price_usd: 0.60,
    wholesale_price_usd: 0.60,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'bebidas-jugo-natural',
    name: 'Jugo Natural',
    description: 'Parchita o mora',
    category: 'BEBIDAS',
    type: 'detal',
    price_usd: 0.60,
    wholesale_price_usd: 0.60,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── POSTRES (nuevo del complemento) ─────────────────────
  {
    id: 'postres-torta-grande',
    name: 'Porción Torta Grande',
    description: 'Porción grande de torta artesanal',
    category: 'POSTRES',
    type: 'detal',
    price_usd: 0.95,
    wholesale_price_usd: 0.95,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-torta-mediana',
    name: 'Porción Torta Mediana',
    description: 'Porción mediana de torta artesanal',
    category: 'POSTRES',
    type: 'detal',
    price_usd: 0.83,
    wholesale_price_usd: 0.83,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-torta-pequeña',
    name: 'Porción Torta Pequeña',
    description: 'Porción pequeña de torta artesanal',
    category: 'POSTRES',
    type: 'detal',
    price_usd: 0.48,
    wholesale_price_usd: 0.48,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-mantecada',
    name: 'Porción Mantecada',
    description: 'Porción de mantecada artesanal',
    category: 'POSTRES',
    type: 'detal',
    price_usd: 0.71,
    wholesale_price_usd: 0.71,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-trufa-grande',
    name: 'Trufa Grande',
    description: 'Trufa de chocolate artesanal grande',
    category: 'POSTRES',
    type: 'detal',
    price_usd: 0.60,
    wholesale_price_usd: 0.60,
    available: true,
    image_url: null,
    is_best_seller: false,
  },
  {
    id: 'postres-pan-de-dios',
    name: 'Pan de Dios',
    description: 'Pan de Dios artesanal',
    category: 'POSTRES',
    type: 'detal',
    price_usd: 1.19,
    wholesale_price_usd: 1.19,
    available: true,
    image_url: null,
    is_best_seller: false,
  },

  // ─── COMBOS (nuevo del complemento) ──────────────────────
  {
    id: 'combo-teq-doble-nestea',
    name: 'Tequeños Doble Queso + Nestea — 3 und',
    description: '3 tequeños doble queso con Nestea incluido',
    category: 'COMBOS',
    type: 'detal',
    price_usd: 1.43,
    wholesale_price_usd: 1.43,
    available: true,
    image_url: null,
    is_best_seller: true,
  },
];

export const categories: ProductCategory[] = [
  'TEQUEÑOS',
  'PASAPALOS',
  'MASAS',
  'PANADERIA',
  'CAFETÍN',
  'SALSAS',
  'BEBIDAS',
  'POSTRES',
  'COMBOS',
];

export const categoryLabels: Record<ProductCategory, string> = {
  'TEQUEÑOS': 'Tequeños',
  PASAPALOS: 'Pasapalos',
  MASAS: 'Masas',
  PANADERIA: 'Panadería',
  'CAFETÍN': 'Cafetín',
  SALSAS: 'Salsas',
  BEBIDAS: 'Bebidas',
  POSTRES: 'Postres',
  COMBOS: 'Combos',
};

/** Emoji por categoría — fuente única (carrito, upsell, tarjetas…). */
export const categoryEmoji: Record<ProductCategory, string> = {
  'TEQUEÑOS': '🧀',
  PASAPALOS: '🍢',
  MASAS: '🥖',
  PANADERIA: '🥐',
  'CAFETÍN': '🍔',
  SALSAS: '🫙',
  BEBIDAS: '🥤',
  POSTRES: '🎂',
  COMBOS: '🎁',
};
