INSERT INTO products (id, name, description, category, type, price_usd, wholesale_price_usd, available, image_url, is_best_seller) VALUES
('tequeno-super-queso', 'Tequeño Super Queso', 'Tequeño súper relleno de queso', 'TEQUEÑOS', 'ambos', 9, 9, true, NULL, true),
('tequeno-super-byq', 'Tequeño Super B y Q', 'Tequeño súper bocadillo y queso', 'TEQUEÑOS', 'ambos', 9.9, 9.9, true, NULL, false),
('tequeno-tyq', 'Tequeño T y Q', 'Tequeño tocineta y queso', 'TEQUEÑOS', 'ambos', 10, 10, true, NULL, false),
('tequeno-tradicional-queso-25', 'Tequeño Tradicional Queso — 25 und', '25 unidades de tequeño tradicional de queso', 'TEQUEÑOS', 'ambos', 5.85, 5.85, true, NULL, true),
('tequeno-tradicional-byq', 'Tequeño Tradicional B y Q', 'Tequeño tradicional bocadillo y queso', 'TEQUEÑOS', 'ambos', 7.32, 7.32, true, NULL, false),
('tequeno-escolar-queso', 'Tequeño Escolar Queso', 'Tequeño tamaño escolar de queso', 'TEQUEÑOS', 'ambos', 6.12, 6.12, true, NULL, false),
('tequeno-escolar-byq', 'Tequeño Escolar B y Q', 'Tequeño escolar bocadillo y queso', 'TEQUEÑOS', 'ambos', 6.45, 6.45, true, NULL, false),
('tequeno-doble-queso', 'Tequeño Doble Queso', 'Tequeño con doble relleno de queso', 'TEQUEÑOS', 'ambos', 7.74, 6.88, true, NULL, true),
('tequeno-doble-surtido', 'Tequeño Doble Surtido', 'Tequeño doble con rellenos variados', 'TEQUEÑOS', 'ambos', 8.61, 8.61, true, NULL, false),
('tequeno-mini-25-combo', 'Tequeño Mini — 25 und Combo', 'Combo de 25 tequeños mini', 'TEQUEÑOS', 'ambos', 2.94, 2.79, true, NULL, false),
('tequeno-normal-queso', 'Tequeño Normal Queso', 'Tequeño tamaño normal de queso', 'TEQUEÑOS', 'ambos', 6.43, 6.43, true, NULL, false),
('tequeno-normal-byq', 'Tequeño Normal B y Q', 'Tequeño normal bocadillo y queso', 'TEQUEÑOS', 'ambos', 7.11, 7.11, true, NULL, false),
('tequeno-normal-tyq', 'Tequeño Normal T y Q', 'Tequeño normal tocineta y queso', 'TEQUEÑOS', 'ambos', 7.13, 7.13, true, NULL, false),
('tequeno-normal-jyq', 'Tequeño Normal J y Q', 'Tequeño normal jamón y queso', 'TEQUEÑOS', 'ambos', 7.11, 7.11, true, NULL, false),
('pasapalos-pollo-carne', 'Pasapalos Pollo/Carne', 'Pasapalos de pollo o carne', 'PASAPALOS', 'ambos', 5.16, 5.16, true, NULL, false),
('bolitas-carne-15', 'Bolitas de Carne — 15 und', '15 unidades de bolitas de carne', 'PASAPALOS', 'ambos', 5.16, 5.16, true, NULL, false),
('morcillitas-25', 'Morcillitas — 25 und', '25 unidades de morcillitas', 'PASAPALOS', 'ambos', 6.45, 6.45, true, NULL, false),
('pastelon-pizza-10', 'Pastelón Pizza — 10 und', '10 unidades de pastelón de pizza', 'PASAPALOS', 'ambos', 5.16, 5.16, true, NULL, false),
('pastelon-ac-10', 'Pastelón A/C — 10 und', '10 unidades de pastelón atún y carne', 'PASAPALOS', 'ambos', 5.58, 5.58, true, NULL, false),
('pastelon-pc-10', 'Pastelón P/C — 10 und', '10 unidades de pastelón pollo y carne', 'PASAPALOS', 'ambos', 9.9, 9.9, true, NULL, false),
('pasapalos-teq-queso-relleno-25', 'Tequeñitos Queso + Relleno — 25 und', '25 tequeñitos de queso con relleno especial', 'PASAPALOS', 'detal', 2.62, 2.62, true, NULL, false),
('pasapalos-teq-byq-relleno-25', 'Tequeñitos Bocadillo + Queso + Relleno — 25 und', '25 tequeñitos de bocadillo, queso y relleno', 'PASAPALOS', 'detal', 3.1, 3.1, true, NULL, false),
('pasapalos-doble-queso-10', 'Doble Queso — 10 und', 'Tequeños doble relleno de queso, 10 unidades', 'PASAPALOS', 'detal', 3.33, 3.33, true, NULL, true),
('pasapalos-pizzas-mini-20', 'Pizzas Mini Básica — 20 und', '20 minipizzas básicas artesanales', 'PASAPALOS', 'detal', 7.14, 7.14, true, NULL, false),
('pasapalos-pastelitos-arrozcarne-15', 'Pastelitos Arroz con Carne — 15 und', '15 pastelitos rellenos de arroz con carne', 'PASAPALOS', 'detal', 1.67, 1.67, true, NULL, false),
('pasapalos-pastelitos-pizza-15', 'Pastelitos Pizza — 15 und', '15 pastelitos sabor pizza', 'PASAPALOS', 'detal', 1.67, 1.67, true, NULL, false),
('pasapalos-pastelitos-surtidos-15', 'Pastelitos Surtidos — 15 und', 'Pollo, carne, jamón+queso y bocadillo+queso', 'PASAPALOS', 'detal', 3.1, 3.1, true, NULL, false),
('pasapalos-empanada', 'Empanada (Mixta/Pollo/Carne)', 'Unidad — mixta, de pollo o de carne', 'PASAPALOS', 'detal', 0.95, 0.95, true, NULL, false),
('masa-750', 'Masa 750 g', 'Masa fácil artesanal 750 gramos', 'MASAS', 'ambos', 2.37, 2.15, true, NULL, false),
('masa-500', 'Masa 500 g', 'Masa fácil artesanal 500 gramos', 'MASAS', 'ambos', 1.5, 1.29, true, NULL, false),
('masa-n4', 'Masa N.4', 'Masa número 4', 'MASAS', 'ambos', 3.18, 3, true, NULL, false),
('masa-n4-h', 'Masa N.4 (H)', 'Masa número 4 especial', 'MASAS', 'ambos', 3.45, 3.45, true, NULL, false),
('masa-n3', 'Masa N.3', 'Masa número 3', 'MASAS', 'ambos', 1.5, 1.29, true, NULL, false),
('masa-n1', 'Masa N.1', 'Masa número 1', 'MASAS', 'ambos', 3.24, 3, true, NULL, false),
('masa-mediana', 'Masa Mediana', 'Masa fácil artesanal presentación mediana', 'MASAS', 'ambos', 1.19, 1.07, true, NULL, false),
('masa-pequeña', 'Masa Pequeña', 'Masa fácil artesanal presentación pequeña', 'MASAS', 'ambos', 0.83, 0.6, true, NULL, false),
('masa-par-hornear', 'Masa Par Hornear', 'Masa lista para hornear en casa', 'MASAS', 'ambos', 1.9, 1.79, true, NULL, false),
('masa-pizza-5', 'Masa para Pizzas — 5 und (23 cm)', 'Pack de 5 masas de pizza artesanal de 23 cm', 'MASAS', 'ambos', 2.38, 2.38, true, NULL, false),
('mayor-super-byq-10', 'Súper Bocadillo y Queso Al Mayor — 10 und', 'Tequeño súper con bocadillo y queso · precio al mayor', 'MASAS', 'mayorista', 5.24, 5.24, true, NULL, false),
('mayor-super-doblequeso-10', 'Súper Doble Queso Al Mayor — 10 und', 'Tequeño súper doble relleno de queso · precio al mayor', 'MASAS', 'mayorista', 5.71, 5.71, true, NULL, false),
('mayor-super-doblebyq-10', 'Súper Doble Bocadillo y Queso Al Mayor — 10 und', 'Tequeño súper doble bocadillo y queso · precio al mayor', 'MASAS', 'mayorista', 6.19, 6.19, true, NULL, false),
('mayor-escolar-queso-10', 'Escolar Queso Al Mayor — 10 und', 'Tequeño escolar relleno de queso · precio al mayor', 'MASAS', 'mayorista', 2.62, 2.62, true, NULL, false),
('mayor-escolar-byq-10', 'Escolar Bocadillo y Queso Al Mayor — 10 und', 'Tequeño escolar bocadillo y queso · precio al mayor', 'MASAS', 'mayorista', 3.1, 3.1, true, NULL, false),
('mayor-escolar-doblequeso-10', 'Escolar Doble Queso Al Mayor — 10 und', 'Tequeño escolar doble relleno de queso · precio al mayor', 'MASAS', 'mayorista', 3.33, 3.33, true, NULL, false),
('mayor-escolar-doblebyq-10', 'Escolar Doble Bocadillo y Queso Al Mayor — 10 und', 'Tequeño escolar doble bocadillo y queso · precio al mayor', 'MASAS', 'mayorista', 4.29, 4.29, true, NULL, false),
('pan-espanol-10', 'Pan Español — 10 und', '10 unidades de pan español', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('pan-dulce', 'Pan Dulce', 'Pan dulce artesanal', 'PANADERIA', 'ambos', 2.97, 2.97, true, NULL, false),
('pan-perro-21', 'Pan de Perro — 21 und', '21 unidades de pan para perro caliente', 'PANADERIA', 'ambos', 3.45, 3.45, true, NULL, true),
('pan-perro-12', 'Pan de Perro — 12 und', '12 unidades de pan para perro caliente', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('pan-perro-mini-10', 'Pan de Perro Mini — 10 und', '10 unidades de pan para perro mini', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('pan-hamburguesa-trad', 'Pan Hamburguesa Tradicional', 'Pan para hamburguesa tradicional', 'PANADERIA', 'ambos', 3.45, 3.45, true, NULL, false),
('pan-whopper', 'Pan Whopper', 'Pan estilo whopper', 'PANADERIA', 'ambos', 3.45, 3.45, true, NULL, false),
('pan-hamburguesa-mini', 'Pan Hamburguesa Mini', 'Pan para hamburguesa mini', 'PANADERIA', 'ambos', 2.58, 2.58, true, NULL, false),
('pan-sandwich-cc', 'Pan Sandwich C/C', 'Pan de sandwich con corteza', 'PANADERIA', 'ambos', 2.79, 2.58, true, NULL, false),
('pan-sandwich-sc', 'Pan Sandwich S/C', 'Pan de sandwich sin corteza', 'PANADERIA', 'ambos', 3, 2.79, true, NULL, false),
('pan-sandwich-integral', 'Pan Sandwich Integral', 'Pan de sandwich integral', 'PANADERIA', 'ambos', 4.45, 4.45, true, NULL, false),
('pan-vegano', 'Pan Vegano', 'Pan artesanal vegano', 'PANADERIA', 'ambos', 4.29, 4.29, true, NULL, false),
('pan-briochet-6', 'Pan Briochet — 6 und', '6 unidades de pan briochet', 'PANADERIA', 'ambos', 3, 3, true, NULL, false),
('pan-banquete-21', 'Pan de Banquete — 21 und', '21 unidades de pan de banquete', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('pan-tostado-salado', 'Pan Tostado Salado', 'Pan tostado sabor salado', 'PANADERIA', 'ambos', 1.74, 1.74, true, NULL, false),
('pan-tostado-dulce', 'Pan Tostado Dulce', 'Pan tostado sabor dulce', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('galletas-pasta-seca', 'Galletas Pasta Seca', 'Galletas de pasta seca artesanales', 'PANADERIA', 'ambos', 2.79, 2.79, true, NULL, false),
('palmeritas-10', 'Palmeritas — 10 und', '10 unidades de palmeritas', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('mantecada-pona', 'Mantecada Poña', 'Mantecada artesanal pequeña', 'PANADERIA', 'ambos', 2.58, 2.58, true, NULL, false),
('mantecada-grande', 'Mantecada Grande', 'Mantecada artesanal grande', 'PANADERIA', 'ambos', 2.58, 2.58, true, NULL, false),
('brazo-gitano', 'Brazo Gitano', 'Brazo gitano artesanal', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('brazo-reina', 'Brazo Reina', 'Brazo reina artesanal', 'PANADERIA', 'ambos', 1.29, 1.29, true, NULL, false),
('trifles', 'Trifles', 'Postre trifles artesanal', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('quesillo', 'Quesillo', 'Quesillo venezolano artesanal', 'PANADERIA', 'ambos', 2.58, 2.58, true, NULL, false),
('torta-tres-leches', 'Torta Tres Leches', 'Torta tres leches artesanal', 'PANADERIA', 'ambos', 3.45, 3.45, true, NULL, true),
('repollitas-20', 'Repollitas — 20 und', '20 unidades de repollitas', 'PANADERIA', 'ambos', 3.45, 3.45, true, NULL, false),
('torta-1kg', 'Torta 1 Kg', 'Torta artesanal de 1 kilogramo', 'PANADERIA', 'ambos', 17.19, 17.19, true, NULL, false),
('torta-media', 'Torta 1/2', 'Torta artesanal media', 'PANADERIA', 'ambos', 12.9, 12.9, true, NULL, false),
('torta-cuarto', 'Torta 1/4', 'Torta artesanal cuarto', 'PANADERIA', 'ambos', 8.61, 8.61, true, NULL, false),
('torta-1kg-combo', 'Torta 1 Kg Combo', 'Combo torta 1 Kg con decoración', 'PANADERIA', 'ambos', 24.54, 24.54, true, NULL, false),
('cascaritas', 'Cascaritas', 'Cascaritas artesanales', 'PANADERIA', 'ambos', 2.16, 2.16, true, NULL, false),
('biscocho-1kg', 'Biscocho 1 Kg', 'Biscocho artesanal 1 kilogramo', 'PANADERIA', 'ambos', 6.81, 6.81, true, NULL, false),
('biscocho-medio', 'Biscocho 1/2 Kg', 'Biscocho artesanal medio kilogramo', 'PANADERIA', 'ambos', 6.45, 6.45, true, NULL, false),
('biscocho-cuarto', 'Biscocho 1/4 Kg', 'Biscocho artesanal cuarto de kilo', 'PANADERIA', 'ambos', 4.3, 4.3, true, NULL, false),
('trufas', 'Trufas', 'Trufas de chocolate artesanales', 'PANADERIA', 'ambos', 1.08, 1.08, true, NULL, false),
('brownie', 'Brownie', 'Brownie artesanal', 'PANADERIA', 'ambos', 3.02, 3.02, true, NULL, false),
('torta-milhoja', 'Torta Milhoja', 'Torta milhoja artesanal', 'PANADERIA', 'ambos', 2.44, 2.44, true, NULL, false),
('gelatinas', 'Gelatinas Sabores', 'Gelatinas en varios sabores', 'PANADERIA', 'ambos', 1.16, 1.16, true, NULL, false),
('pan-sandwich-integral-pequeño', 'Sandwich Integral Pequeño', 'Pan sandwich integral artesanal pequeño', 'PANADERIA', 'detal', 1.9, 1.9, true, NULL, false),
('pan-sandwich-normal-grande', 'Sandwich Normal Grande', 'Pan sandwich normal artesanal grande', 'PANADERIA', 'detal', 1.9, 1.9, true, NULL, false),
('pan-sandwich-normal-pequeño', 'Sandwich Normal Pequeño', 'Pan sandwich normal artesanal pequeño', 'PANADERIA', 'detal', 1.43, 1.43, true, NULL, false),
('pan-sandwich-multicereales', 'Sandwich Multicereales', 'Pan sandwich artesanal multicereales', 'PANADERIA', 'detal', 2.38, 2.38, true, NULL, false),
('cafetín-hamburguesa', 'Hamburguesa + Nestea', 'Hamburguesa en pan de ajillo con Nestea incluido', 'CAFETÍN', 'detal', 3.33, 3.33, true, NULL, false),
('cafetín-pizza-personal', 'Pizza Personal + Nestea', 'Pizza personal artesanal con Nestea incluido', 'CAFETÍN', 'detal', 1.67, 1.67, true, NULL, false),
('cafetín-perro-caliente', 'Perro Caliente', 'No disponible por el momento', 'CAFETÍN', 'detal', 0, 0, false, NULL, false),
('mayonesa-premium', 'Mayonesa Premium', 'Mayonesa artesanal premium', 'SALSAS', 'ambos', 19.66, 19.66, true, NULL, false),
('mayonesa-rindemax', 'Mayonesa Rindemax', 'Mayonesa Rindemax artesanal', 'SALSAS', 'ambos', 7.74, 7.74, true, NULL, false),
('salsa-bbq', 'Salsa B.B.Q', 'Salsa barbecue artesanal', 'SALSAS', 'ambos', 9.9, 7.74, true, NULL, false),
('salsa-cheddar', 'Salsa Cheddar', 'Salsa cheddar artesanal', 'SALSAS', 'ambos', 9.9, 7.74, true, NULL, false),
('salsa-mostaza', 'Salsa Mostaza', 'Salsa de mostaza artesanal', 'SALSAS', 'ambos', 9.9, 7.74, true, NULL, false),
('salsa-ketchup', 'Salsa Ketchup', 'Salsa ketchup artesanal', 'SALSAS', 'ambos', 9.9, 9.9, true, NULL, false),
('salsa-sabores-preparados', 'Salsa Sabores Preparados', 'Salsa con sabores especiales preparados', 'SALSAS', 'ambos', 2.44, 2.44, true, NULL, false),
('coca-2lt', 'Coca Cola 2 Lt', 'Coca Cola 2 litros', 'BEBIDAS', 'ambos', 2.37, 2.15, true, NULL, false),
('coca-15lt', 'Coca Cola 1½ Lt', 'Coca Cola 1.5 litros', 'BEBIDAS', 'ambos', 1.95, 1.95, true, NULL, false),
('coca-355', 'Coca Cola 355 ml', 'Coca Cola lata 355ml', 'BEBIDAS', 'ambos', 1.08, 1.08, true, NULL, false),
('agua-355', 'Agua 355 ml', 'Agua mineral 355ml', 'BEBIDAS', 'ambos', 1.08, 1.08, true, NULL, false),
('agua-600', 'Agua 600 ml', 'Agua mineral 600ml', 'BEBIDAS', 'ambos', 1.5, 1.5, true, NULL, false),
('agua-5lt', 'Agua 5 Lt', 'Agua mineral 5 litros', 'BEBIDAS', 'ambos', 1.95, 1.5, true, NULL, false),
('jugo-valle-500', 'Jugo del Valle 500 ml', 'Jugo del Valle 500ml', 'BEBIDAS', 'ambos', 1.29, 1.29, true, NULL, false),
('jugo-valle-1lt', 'Jugo del Valle 1 Lt', 'Jugo del Valle 1 litro', 'BEBIDAS', 'ambos', 1.95, 1.95, true, NULL, false),
('bebidas-malta', 'Malta', 'Malta fría', 'BEBIDAS', 'detal', 0.71, 0.71, true, NULL, false),
('bebidas-maxi', 'Maxi', 'Bebida Maxi', 'BEBIDAS', 'detal', 0.48, 0.48, true, NULL, false),
('bebidas-masato', 'Masato', 'Masato artesanal', 'BEBIDAS', 'detal', 0.6, 0.6, true, NULL, false),
('bebidas-jugo-natural', 'Jugo Natural', 'Parchita o mora', 'BEBIDAS', 'detal', 0.6, 0.6, true, NULL, false),
('postres-torta-mediana', 'Porción Torta Mediana', 'Porción mediana de torta artesanal', 'POSTRES', 'detal', 0.83, 0.83, true, NULL, false),
('postres-torta-pequeña', 'Porción Torta Pequeña', 'Porción pequeña de torta artesanal', 'POSTRES', 'detal', 0.48, 0.48, true, NULL, false),
('postres-mantecada', 'Porción Mantecada', 'Porción de mantecada artesanal', 'POSTRES', 'detal', 0.71, 0.71, true, NULL, false),
('postres-trufa-grande', 'Trufa Grande', 'Trufa de chocolate artesanal grande', 'POSTRES', 'detal', 0.6, 0.6, true, NULL, false),
('postres-pan-de-dios', 'Pan de Dios', 'Pan de Dios artesanal', 'POSTRES', 'detal', 1.19, 1.19, true, NULL, false)
ON CONFLICT (id) DO NOTHING;